/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;
import java.awt.Color;
import java.awt.event.KeyEvent;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JTextPane;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultStyledDocument;
import javax.swing.text.Element;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;

/**
 *
 * @author Enrique Miramontes
 */
public class FeedIT extends javax.swing.JFrame {
    //DEclaracion de variables globales
    NumeroLinea numerolinea;
    DefaultStyledDocument doc;
    /**
     * Creates new form FeedIT
     */
    public FeedIT() {
        initComponents();
        iniciarComponentes();
    }   
    // Metodo para iniciar los componentes
    private void iniciarComponentes(){
        setTitle("Feed-IT");
        setLocationRelativeTo(null);
        //Se agregan las Lineas
        numerolinea = new NumeroLinea(jtpCode);
        scrollCode.setRowHeaderView(numerolinea);
    }//end iniciarComponentes
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scrollCode = new javax.swing.JScrollPane();
        jtpCode = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel_Funciones = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btn_Sintactico = new javax.swing.JButton();
        btn_Lexico = new javax.swing.JButton();
        btn_CodigoMedio = new javax.swing.JButton();
        btn_CodigoObjeto = new javax.swing.JButton();
        btn_Compilar = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jToolBar_Informacion = new javax.swing.JToolBar();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btn_Simbolos = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btn_Gramaticas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jtpCode.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jtpCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtpCodeKeyPressed(evt);
            }
        });
        scrollCode.setViewportView(jtpCode);

        txtLog.setColumns(20);
        txtLog.setRows(5);
        jScrollPane2.setViewportView(txtLog);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollCode, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1238, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollCode, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 1250, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 50));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos_claro/guardar_claro.png"))); // NOI18N

        btn_Sintactico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos_claro/analisis_sintactico.png"))); // NOI18N

        btn_Lexico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos_claro/analisis_lexico.png"))); // NOI18N

        btn_CodigoMedio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos_claro/codigo_medio.png"))); // NOI18N

        btn_CodigoObjeto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos_claro/codigo_objeto.png"))); // NOI18N

        btn_Compilar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos_claro/compilar_claro.png"))); // NOI18N

        btn_Salir.setBackground(new java.awt.Color(255, 51, 51));
        btn_Salir.setForeground(new java.awt.Color(255, 51, 51));
        btn_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_FuncionesLayout = new javax.swing.GroupLayout(jPanel_Funciones);
        jPanel_Funciones.setLayout(jPanel_FuncionesLayout);
        jPanel_FuncionesLayout.setHorizontalGroup(
            jPanel_FuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_FuncionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel_FuncionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_FuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Lexico, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Sintactico, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_CodigoMedio, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_CodigoObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Compilar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_FuncionesLayout.setVerticalGroup(
            jPanel_FuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_FuncionesLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Lexico, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Sintactico, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(btn_Compilar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_CodigoMedio, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_CodigoObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(btn_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel_Funciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 60, 640));

        jToolBar_Informacion.setRollover(true);
        jToolBar_Informacion.add(jSeparator2);

        btn_Simbolos.setText("Tabla de Simbolos");
        btn_Simbolos.setFocusable(false);
        btn_Simbolos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Simbolos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Simbolos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SimbolosActionPerformed(evt);
            }
        });
        jToolBar_Informacion.add(btn_Simbolos);
        jToolBar_Informacion.add(jSeparator1);

        btn_Gramaticas.setText("Gramáticas Generadas");
        btn_Gramaticas.setFocusable(false);
        btn_Gramaticas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Gramaticas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Gramaticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GramaticasActionPerformed(evt);
            }
        });
        jToolBar_Informacion.add(btn_Gramaticas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar_Informacion, javax.swing.GroupLayout.DEFAULT_SIZE, 1250, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar_Informacion, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 1250, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtpCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtpCodeKeyPressed
         switch (evt.getKeyCode()) {
            case KeyEvent.VK_LEFT:
                jtpCode.setCaretPosition(jtpCode.getCaretPosition());
                break;
            case KeyEvent.VK_RIGHT:
                jtpCode.setCaretPosition(jtpCode.getCaretPosition());
                break;
            case KeyEvent.VK_DOWN:
                jtpCode.setCaretPosition(jtpCode.getCaretPosition());
                break;
            case KeyEvent.VK_UP:
                jtpCode.setCaretPosition(jtpCode.getCaretPosition());
                break;
              case KeyEvent.VK_TAB:
                evt.consume();
                String tab = "  ";
                int posicion = jtpCode.getCaretPosition();
                Element e = doc.getCharacterElement(posicion);
                try {
                    doc.insertString(posicion, tab, e.getAttributes());
                } catch (BadLocationException ex) {
                    showMessageDialog(this, "Error en la posicion del cursor");
                }
                break;
            default:
                   colors();
         }//end swhitch
    }//GEN-LAST:event_jtpCodeKeyPressed

    private void btn_SimbolosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SimbolosActionPerformed
        TablaSimbolos ts = new TablaSimbolos();
        ts.setVisible(true);
    }//GEN-LAST:event_btn_SimbolosActionPerformed

    private void btn_GramaticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GramaticasActionPerformed
        TablaGramaticas tg = new TablaGramaticas();
        tg.setVisible(true);
    }//GEN-LAST:event_btn_GramaticasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FeedIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FeedIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FeedIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FeedIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FeedIT().setVisible(true);
            }
        });
    }
        
    //---------------------------------------------------Metodos para pintar las palabras Reservadas-----------------------------------------------------------
  
    //Metodo para encontrar las ultimas cadenas
    private int findLastNonWordChar(String texto, int i){
        while(--i >= 0){
            if(String.valueOf(texto.charAt(i)).matches("[\\s;=(){}]")){
                break;
            }//if
        }//while
        
        return i;
    }//end findLast
    
    
    //Metodo para encontrar las primeras cadenas
    private int findFirstNonWordChar(String texto, int i){
        while(i < texto.length()){
            if(String.valueOf(texto.charAt(i)).matches("[\\s;=(){}]")){
                break;
            }//if
            i++;
        }//while
        return i;
    }//end findFirst
    
    //Metodo para pintar las palabras reservadas
    private void colors(){
        int p = jtpCode.getCaretPosition();
        final StyleContext cont = StyleContext.getDefaultStyleContext();
        //Colores
        final AttributeSet attAzul  =  cont.addAttribute(cont.getEmptySet(), StyleConstants.Foreground, new Color(51,115,255));
        final AttributeSet attNegro =  cont.addAttribute(cont.getEmptySet(), StyleConstants.Foreground, new Color(0,0,0));
        final AttributeSet attVerde =  cont.addAttribute(cont.getEmptySet(), StyleConstants.Foreground, new Color(71,158,1));
        final AttributeSet attGris  =  cont.addAttribute(cont.getEmptySet(), StyleConstants.Foreground, new Color(121,125,133));
         //Style
          doc = new DefaultStyledDocument(){
             public void insertString(int offset, String str, AttributeSet a)throws BadLocationException{
                 super.insertString(offset, str,  a);
                 String text = getText(0,getLength());
                 int before = findLastNonWordChar(text, offset);
                 if(before < 0){
                     before = 0;
                 }//if
                 int after = findFirstNonWordChar(text, offset + str.length());
                 int wordL = before;
                 int wordR = before;
                 while(wordR <= after){
                     if(wordR == after || String.valueOf(text.charAt(wordR)).matches("[\\s;=(){}]")){
                         if(text.substring(wordL,wordR).matches("[\\s]*(class|fun|main|int|float|string|double|null|boolean|"
                                 + "humedad|fagua|peso|fcomer|fpremio|fmasaje|fluz|fjuguete|candil|when|if|else|true|false|"
                                 + "for|forEach|do|const|goBack|loop|and|or|not|while)")){
                             setCharacterAttributes(wordL,wordR - wordL,  attAzul,false);
                         }//second if
                         else if(text.substring(wordL,wordR).matches("[\\s=(]*(\"\\w*\")")){
                             setCharacterAttributes(wordL,wordR - wordL,attVerde,false);
                         }//tercer if
                          else if(text.substring(wordL,wordR).matches("\\s*[#]+\\w*" )){
                             setCharacterAttributes(wordL,wordR - wordL,attGris,false);
                         }//tercer if
                         else{
                             setCharacterAttributes(wordL,wordR - wordL,attNegro,false);
                         }//end else 
                         
                         wordL = wordR;
                     }//first if
                     wordR++;
                 }//end while    
             }//end insertString

              
             public void remove(int offs, int len)throws BadLocationException{
                 super.remove(offs, len);
                 String text = getText(0,getLength());
                 int before = findLastNonWordChar(text, offs);
                 if(before < 0){
                     before = 0;
                 }//end if
                 
             }//end remove
             
         };//end doc
        
         JTextPane txt = new JTextPane(doc);
         String temp = jtpCode.getText();
         jtpCode.setStyledDocument(txt.getStyledDocument());
         jtpCode.setText(temp);
         jtpCode.setCaretPosition(p);     
    }//end colors
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btn_CodigoMedio;
    private javax.swing.JButton btn_CodigoObjeto;
    private javax.swing.JButton btn_Compilar;
    private javax.swing.JButton btn_Gramaticas;
    private javax.swing.JButton btn_Lexico;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JButton btn_Simbolos;
    private javax.swing.JButton btn_Sintactico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_Funciones;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar_Informacion;
    private javax.swing.JTextPane jtpCode;
    private javax.swing.JScrollPane scrollCode;
    private javax.swing.JTextArea txtLog;
    // End of variables declaration//GEN-END:variables
}
