
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 25 23:40:31 MST 2021
//----------------------------------------------------

package analizador_sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Or = 30;
  public static final int Class = 18;
  public static final int True = 32;
  public static final int Double = 6;
  public static final int Null = 7;
  public static final int If = 20;
  public static final int Potencia = 42;
  public static final int Candil = 17;
  public static final int Fmasaje = 14;
  public static final int MayorIgualQue = 46;
  public static final int Else = 21;
  public static final int Asignacion = 35;
  public static final int ExactamenteIgual = 37;
  public static final int Fjuguete = 16;
  public static final int Salto_Linea = 53;
  public static final int Llave_C = 52;
  public static final int While = 34;
  public static final int Llave_A = 51;
  public static final int Division = 41;
  public static final int Int = 3;
  public static final int Flotante = 57;
  public static final int Peso = 11;
  public static final int Float = 4;
  public static final int Modulo = 43;
  public static final int For = 23;
  public static final int P_coma = 54;
  public static final int EOF = 0;
  public static final int Premio = 13;
  public static final int MayorQue = 44;
  public static final int Not = 31;
  public static final int And = 29;
  public static final int error = 1;
  public static final int Fagua = 10;
  public static final int MenorIgualQue = 47;
  public static final int When = 19;
  public static final int Fun = 27;
  public static final int False = 33;
  public static final int ERROR = 58;
  public static final int Do = 24;
  public static final int GoBack = 26;
  public static final int Const = 25;
  public static final int String = 5;
  public static final int Fluz = 15;
  public static final int Parentesis_C = 50;
  public static final int Identificador = 55;
  public static final int Fcomer = 12;
  public static final int Parentesis_A = 49;
  public static final int Resta = 39;
  public static final int MenorQue = 45;
  public static final int DiferenteDe = 48;
  public static final int Multiplicacion = 40;
  public static final int Boolean = 8;
  public static final int Humedad = 9;
  public static final int Numero = 56;
  public static final int Suma = 38;
  public static final int Loop = 28;
  public static final int Main = 2;
  public static final int ForEach = 22;
  public static final int Igual = 36;
}

