
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 07 01:35:50 MST 2021
//----------------------------------------------------

package analizador_sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Or = 19;
  public static final int Class = 3;
  public static final int True = 43;
  public static final int Coma = 6;
  public static final int Double = 30;
  public static final int Null = 31;
  public static final int If = 38;
  public static final int Dec = 25;
  public static final int Potencia = 16;
  public static final int Candil = 56;
  public static final int Fpremio = 52;
  public static final int Fmasaje = 53;
  public static final int Else = 39;
  public static final int Asignacion = 21;
  public static final int Fjuguete = 55;
  public static final int Salto_Linea = 11;
  public static final int Llave_C = 10;
  public static final int While = 45;
  public static final int Division = 15;
  public static final int Int = 27;
  public static final int Llave_A = 9;
  public static final int Flotante = 34;
  public static final int OpR = 23;
  public static final int Peso = 50;
  public static final int Float = 28;
  public static final int Modulo = 17;
  public static final int For = 40;
  public static final int EOF = 0;
  public static final int P_coma = 5;
  public static final int Not = 20;
  public static final int And = 18;
  public static final int Fagua = 49;
  public static final int error = 1;
  public static final int Texto = 35;
  public static final int Fun = 4;
  public static final int False = 44;
  public static final int Inc = 24;
  public static final int Do = 41;
  public static final int ERROR = 26;
  public static final int GoBack = 42;
  public static final int Time = 57;
  public static final int Const = 37;
  public static final int String = 29;
  public static final int Fluz = 54;
  public static final int Parentesis_C = 8;
  public static final int Fcomer = 51;
  public static final int Identificador = 36;
  public static final int Parentesis_A = 7;
  public static final int Resta = 13;
  public static final int Boolean = 32;
  public static final int Multiplicacion = 14;
  public static final int Humedad = 48;
  public static final int Numero = 33;
  public static final int Suma = 12;
  public static final int Loop = 47;
  public static final int ForEach = 46;
  public static final int Main = 2;
  public static final int Igual = 22;
}

