/* The following code was generated by JFlex 1.4.3 on 6/12/21 0:13 */

package analizador_lexico;
import static analizador_lexico.Tokens.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 6/12/21 0:13 from the specification file
 * <tt>C:/Feed-IT/Feed-IT/src/analizador_lexico/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\36\2\0\1\3\22\0\1\3\1\47\1\56\1\35"+
    "\1\0\1\44\2\0\1\50\1\51\1\43\1\41\1\3\1\42\1\55"+
    "\1\37\12\2\1\0\1\54\1\46\1\40\1\45\2\0\1\4\1\33"+
    "\2\4\1\32\25\4\4\0\1\1\1\0\1\6\1\22\1\26\1\20"+
    "\1\23\1\12\1\17\1\24\1\7\1\27\1\34\1\13\1\5\1\10"+
    "\1\14\1\25\1\1\1\16\1\15\1\11\1\21\1\1\1\31\2\1"+
    "\1\30\1\52\1\0\1\53\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\21\2\1\4\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\1\1\16\1\17\1\20\1\21\1\22\1\1\1\0"+
    "\3\2\1\23\15\2\1\24\2\2\1\25\10\2\1\0"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\0"+
    "\1\35\1\36\1\2\1\37\1\40\1\41\10\2\1\42"+
    "\1\43\20\2\1\0\1\44\1\45\1\46\1\47\4\2"+
    "\1\50\4\2\1\51\4\2\1\52\1\2\1\53\4\2"+
    "\1\54\1\4\1\2\1\55\1\56\1\57\12\2\1\60"+
    "\1\61\1\62\3\2\1\63\1\2\1\64\1\65\1\66"+
    "\2\2\1\67\1\70\1\71\1\72\1\2\1\73\1\74"+
    "\1\75";

  private static int [] zzUnpackAction() {
    int [] result = new int[173];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\274\0\353\0\u011a\0\u0149"+
    "\0\u0178\0\u01a7\0\u01d6\0\u0205\0\u0234\0\u0263\0\u0292\0\u02c1"+
    "\0\u02f0\0\u031f\0\u034e\0\u037d\0\u03ac\0\u03db\0\u040a\0\57"+
    "\0\u0439\0\u0468\0\u0497\0\u04c6\0\u04f5\0\57\0\u0524\0\u0553"+
    "\0\u0582\0\57\0\57\0\57\0\57\0\57\0\u05b1\0\u05e0"+
    "\0\u060f\0\u063e\0\u066d\0\136\0\u069c\0\u06cb\0\u06fa\0\u0729"+
    "\0\u0758\0\u0787\0\u07b6\0\u07e5\0\u0814\0\u0843\0\u0872\0\u08a1"+
    "\0\u08d0\0\136\0\u08ff\0\u092e\0\u095d\0\u098c\0\u09bb\0\u09ea"+
    "\0\u0a19\0\u0a48\0\u0a77\0\u0aa6\0\u0ad5\0\u0b04\0\57\0\57"+
    "\0\57\0\57\0\57\0\57\0\57\0\u05b1\0\57\0\u05e0"+
    "\0\u0b33\0\136\0\136\0\136\0\u0b62\0\u0b91\0\u0bc0\0\u0bef"+
    "\0\u0c1e\0\u0c4d\0\u0c7c\0\u0cab\0\u0cda\0\136\0\u0d09\0\u0d38"+
    "\0\u0d67\0\u0d96\0\u0dc5\0\u0df4\0\u0e23\0\u0e52\0\u0e81\0\u0eb0"+
    "\0\u0edf\0\u0f0e\0\u0f3d\0\u0f6c\0\u0f9b\0\u0fca\0\u0ff9\0\136"+
    "\0\136\0\136\0\136\0\u1028\0\u1057\0\u1086\0\u10b5\0\136"+
    "\0\u10e4\0\u1113\0\u1142\0\u1171\0\136\0\u11a0\0\u11cf\0\u11fe"+
    "\0\u122d\0\136\0\u125c\0\136\0\u128b\0\u12ba\0\u12e9\0\u1318"+
    "\0\136\0\57\0\u1347\0\136\0\136\0\136\0\u1376\0\u13a5"+
    "\0\u13d4\0\u1403\0\u1432\0\u1461\0\u1490\0\u14bf\0\u14ee\0\u151d"+
    "\0\136\0\136\0\136\0\u154c\0\u157b\0\u15aa\0\136\0\u15d9"+
    "\0\136\0\136\0\136\0\u1608\0\u1637\0\136\0\136\0\136"+
    "\0\136\0\u1666\0\136\0\136\0\136";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[173];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\3\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\3\1\17"+
    "\1\20\1\3\1\21\1\22\1\23\1\24\1\25\2\3"+
    "\1\26\3\3\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\2\1\47\60\0\2\3\1\0\31\3"+
    "\24\0\1\4\52\0\1\50\4\0\1\5\54\0\2\3"+
    "\1\0\2\3\1\51\26\3\23\0\2\3\1\0\4\3"+
    "\1\52\24\3\23\0\2\3\1\0\4\3\1\53\1\3"+
    "\1\54\22\3\23\0\2\3\1\0\10\3\1\55\4\3"+
    "\1\56\13\3\23\0\2\3\1\0\3\3\1\57\6\3"+
    "\1\60\16\3\23\0\2\3\1\0\1\3\1\61\1\62"+
    "\4\3\1\63\1\64\4\3\1\65\3\3\1\66\1\67"+
    "\1\70\5\3\23\0\2\3\1\0\10\3\1\71\20\3"+
    "\23\0\2\3\1\0\12\3\1\72\16\3\23\0\2\3"+
    "\1\0\5\3\1\73\23\3\23\0\2\3\1\0\10\3"+
    "\1\74\20\3\23\0\2\3\1\0\10\3\1\75\20\3"+
    "\23\0\2\3\1\0\10\3\1\76\20\3\23\0\2\3"+
    "\1\0\7\3\1\77\21\3\23\0\2\3\1\0\15\3"+
    "\1\100\13\3\23\0\2\3\1\0\17\3\1\101\11\3"+
    "\23\0\2\3\1\0\2\3\1\102\4\3\1\103\1\104"+
    "\20\3\23\0\2\3\1\0\20\3\1\105\10\3\22\0"+
    "\36\27\1\0\20\27\35\0\1\106\61\0\1\107\57\0"+
    "\1\110\17\0\1\4\37\0\1\111\57\0\1\112\53\0"+
    "\1\113\56\0\1\114\56\0\1\115\20\0\3\116\25\0"+
    "\2\116\22\0\1\117\2\0\1\120\55\0\2\3\1\0"+
    "\3\3\1\121\25\3\23\0\2\3\1\0\14\3\1\122"+
    "\14\3\23\0\2\3\1\0\5\3\1\123\23\3\23\0"+
    "\2\3\1\0\5\3\1\124\23\3\23\0\2\3\1\0"+
    "\7\3\1\125\21\3\23\0\2\3\1\0\1\3\1\126"+
    "\27\3\23\0\2\3\1\0\15\3\1\127\13\3\23\0"+
    "\2\3\1\0\2\3\1\130\26\3\23\0\2\3\1\0"+
    "\7\3\1\131\3\3\1\132\15\3\23\0\2\3\1\0"+
    "\10\3\1\133\4\3\1\134\13\3\23\0\2\3\1\0"+
    "\12\3\1\135\16\3\23\0\2\3\1\0\4\3\1\136"+
    "\24\3\23\0\2\3\1\0\12\3\1\137\16\3\23\0"+
    "\2\3\1\0\10\3\1\140\20\3\23\0\2\3\1\0"+
    "\15\3\1\141\13\3\23\0\2\3\1\0\10\3\1\142"+
    "\20\3\23\0\2\3\1\0\12\3\1\143\16\3\23\0"+
    "\2\3\1\0\27\3\1\144\1\3\23\0\2\3\1\0"+
    "\15\3\1\145\13\3\23\0\2\3\1\0\10\3\1\146"+
    "\20\3\23\0\2\3\1\0\11\3\1\147\17\3\23\0"+
    "\2\3\1\0\1\3\1\150\27\3\23\0\2\3\1\0"+
    "\11\3\1\151\17\3\23\0\2\3\1\0\4\3\1\152"+
    "\24\3\23\0\2\3\1\0\2\3\1\153\26\3\23\0"+
    "\2\3\1\0\4\3\1\154\24\3\23\0\2\3\1\0"+
    "\3\3\1\155\13\3\1\156\11\3\22\0\35\106\1\157"+
    "\21\106\1\0\2\3\1\0\4\3\1\160\24\3\23\0"+
    "\2\3\1\0\7\3\1\161\21\3\23\0\2\3\1\0"+
    "\17\3\1\162\11\3\23\0\2\3\1\0\17\3\1\163"+
    "\11\3\23\0\2\3\1\0\11\3\1\164\17\3\23\0"+
    "\2\3\1\0\11\3\1\165\17\3\23\0\2\3\1\0"+
    "\15\3\1\166\13\3\23\0\2\3\1\0\2\3\1\167"+
    "\26\3\23\0\2\3\1\0\24\3\1\170\4\3\23\0"+
    "\2\3\1\0\26\3\1\171\2\3\23\0\2\3\1\0"+
    "\17\3\1\172\11\3\23\0\2\3\1\0\1\3\1\173"+
    "\27\3\23\0\2\3\1\0\13\3\1\174\15\3\23\0"+
    "\2\3\1\0\21\3\1\175\7\3\23\0\2\3\1\0"+
    "\3\3\1\176\25\3\23\0\2\3\1\0\2\3\1\177"+
    "\26\3\23\0\2\3\1\0\16\3\1\200\12\3\23\0"+
    "\2\3\1\0\7\3\1\201\21\3\23\0\2\3\1\0"+
    "\17\3\1\202\11\3\23\0\2\3\1\0\17\3\1\203"+
    "\11\3\23\0\2\3\1\0\10\3\1\204\20\3\23\0"+
    "\2\3\1\0\14\3\1\205\14\3\23\0\2\3\1\0"+
    "\11\3\1\206\17\3\23\0\2\3\1\0\11\3\1\207"+
    "\17\3\23\0\2\3\1\0\7\3\1\210\21\3\23\0"+
    "\2\3\1\0\4\3\1\211\24\3\22\0\35\106\1\157"+
    "\1\106\1\212\17\106\1\0\2\3\1\0\2\3\1\213"+
    "\26\3\23\0\2\3\1\0\17\3\1\214\11\3\23\0"+
    "\2\3\1\0\2\3\1\215\26\3\23\0\2\3\1\0"+
    "\5\3\1\216\23\3\23\0\2\3\1\0\2\3\1\217"+
    "\26\3\23\0\2\3\1\0\1\3\1\220\27\3\23\0"+
    "\2\3\1\0\17\3\1\221\11\3\23\0\2\3\1\0"+
    "\15\3\1\222\13\3\23\0\2\3\1\0\4\3\1\223"+
    "\24\3\23\0\2\3\1\0\22\3\1\224\6\3\23\0"+
    "\2\3\1\0\7\3\1\225\21\3\23\0\2\3\1\0"+
    "\17\3\1\226\11\3\23\0\2\3\1\0\14\3\1\227"+
    "\14\3\23\0\2\3\1\0\3\3\1\230\25\3\23\0"+
    "\2\3\1\0\11\3\1\231\17\3\23\0\2\3\1\0"+
    "\5\3\1\232\23\3\23\0\2\3\1\0\17\3\1\233"+
    "\11\3\23\0\2\3\1\0\23\3\1\234\5\3\23\0"+
    "\2\3\1\0\22\3\1\235\6\3\23\0\2\3\1\0"+
    "\3\3\1\236\25\3\23\0\2\3\1\0\12\3\1\237"+
    "\16\3\23\0\2\3\1\0\17\3\1\240\11\3\23\0"+
    "\2\3\1\0\13\3\1\241\15\3\23\0\2\3\1\0"+
    "\30\3\1\242\23\0\2\3\1\0\17\3\1\243\11\3"+
    "\23\0\2\3\1\0\2\3\1\244\26\3\23\0\2\3"+
    "\1\0\2\3\1\245\26\3\23\0\2\3\1\0\7\3"+
    "\1\246\21\3\23\0\2\3\1\0\17\3\1\247\11\3"+
    "\23\0\2\3\1\0\20\3\1\250\10\3\23\0\2\3"+
    "\1\0\10\3\1\251\20\3\23\0\2\3\1\0\5\3"+
    "\1\252\23\3\23\0\2\3\1\0\4\3\1\253\24\3"+
    "\23\0\2\3\1\0\14\3\1\254\14\3\23\0\2\3"+
    "\1\0\17\3\1\255\11\3\22\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5781];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\25\1\1\11\5\1\1\11\3\1\5\11"+
    "\1\1\1\0\35\1\1\0\7\11\1\0\1\11\37\1"+
    "\1\0\32\1\1\11\43\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[173];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 130) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 22: 
          { lexeme = yytext(); return Igual;
          }
        case 62: break;
        case 52: 
          { lexeme = yytext(); return String;
          }
        case 63: break;
        case 47: 
          { lexeme = yytext(); return Float;
          }
        case 64: break;
        case 25: 
          { lexeme = yytext(); return Potencia;
          }
        case 65: break;
        case 50: 
          { lexeme = yytext(); return While;
          }
        case 66: break;
        case 40: 
          { lexeme = yytext(); return Fluz;
          }
        case 67: break;
        case 7: 
          { lexeme = yytext(); return Asignacion;
          }
        case 68: break;
        case 26: 
          { lexeme = yytext(); return MayorIgualQue;
          }
        case 69: break;
        case 51: 
          { lexeme = yytext(); return Fcomer;
          }
        case 70: break;
        case 49: 
          { lexeme = yytext(); return Const;
          }
        case 71: break;
        case 37: 
          { lexeme = yytext(); return Null;
          }
        case 72: break;
        case 3: 
          { lexeme = yytext(); return Numero;
          }
        case 73: break;
        case 55: 
          { lexeme = yytext(); return Candil;
          }
        case 74: break;
        case 19: 
          { lexeme = yytext(); return If;
          }
        case 75: break;
        case 53: 
          { lexeme = yytext(); return GoBack;
          }
        case 76: break;
        case 59: 
          { lexeme = yytext(); return Boolean;
          }
        case 77: break;
        case 43: 
          { lexeme = yytext(); return Peso;
          }
        case 78: break;
        case 2: 
          { lexeme = yytext(); return Identificador;
          }
        case 79: break;
        case 8: 
          { lexeme = yytext(); return Suma;
          }
        case 80: break;
        case 29: 
          { lexeme = yytext(); return Texto;
          }
        case 81: break;
        case 35: 
          { lexeme = yytext(); return Fun;
          }
        case 82: break;
        case 15: 
          { lexeme = yytext();return Parentesis_C;
          }
        case 83: break;
        case 31: 
          { lexeme = yytext(); return And;
          }
        case 84: break;
        case 33: 
          { lexeme = yytext(); return Not;
          }
        case 85: break;
        case 18: 
          { return P_coma;
          }
        case 86: break;
        case 32: 
          { lexeme = yytext(); return Int;
          }
        case 87: break;
        case 42: 
          { lexeme = yytext(); return Else;
          }
        case 88: break;
        case 60: 
          { lexeme = yytext(); return Humedad;
          }
        case 89: break;
        case 16: 
          { lexeme = yytext();return Llave_A;
          }
        case 90: break;
        case 44: 
          { lexeme = yytext(); return When;
          }
        case 91: break;
        case 28: 
          { lexeme = yytext(); return DiferenteDe;
          }
        case 92: break;
        case 39: 
          { lexeme = yytext(); return True;
          }
        case 93: break;
        case 24: 
          { lexeme = yytext(); return Decremento;
          }
        case 94: break;
        case 20: 
          { lexeme = yytext(); return Or;
          }
        case 95: break;
        case 54: 
          { lexeme = yytext(); return Double;
          }
        case 96: break;
        case 23: 
          { lexeme = yytext(); return Incremento;
          }
        case 97: break;
        case 45: 
          { lexeme = yytext(); return False;
          }
        case 98: break;
        case 41: 
          { lexeme = yytext(); return Loop;
          }
        case 99: break;
        case 46: 
          { lexeme = yytext(); return Fagua;
          }
        case 100: break;
        case 56: 
          { lexeme = yytext(); return Fmasaje;
          }
        case 101: break;
        case 6: 
          { lexeme = yytext(); return Division;
          }
        case 102: break;
        case 12: 
          { lexeme = yytext(); return MayorQue;
          }
        case 103: break;
        case 34: 
          { lexeme = yytext(); return For;
          }
        case 104: break;
        case 61: 
          { lexeme = yytext(); return Fjuguete;
          }
        case 105: break;
        case 30: 
          { lexeme = yytext(); return Flotante;
          }
        case 106: break;
        case 9: 
          { lexeme = yytext(); return Resta;
          }
        case 107: break;
        case 38: 
          { lexeme = yytext(); return Time;
          }
        case 108: break;
        case 5: 
          { return Salto_Linea;
          }
        case 109: break;
        case 17: 
          { lexeme = yytext();return Llave_C;
          }
        case 110: break;
        case 1: 
          { return ERROR;
          }
        case 111: break;
        case 11: 
          { lexeme = yytext(); return Modulo;
          }
        case 112: break;
        case 21: 
          { lexeme = yytext(); return Do;
          }
        case 113: break;
        case 57: 
          { lexeme = yytext(); return ForEach;
          }
        case 114: break;
        case 10: 
          { lexeme = yytext(); return Multiplicacion;
          }
        case 115: break;
        case 4: 
          { /*Ignore*/
          }
        case 116: break;
        case 13: 
          { lexeme = yytext(); return MenorQue;
          }
        case 117: break;
        case 36: 
          { lexeme = yytext(); return Main;
          }
        case 118: break;
        case 27: 
          { lexeme = yytext(); return MenorIgualQue;
          }
        case 119: break;
        case 58: 
          { lexeme = yytext(); return FPremio;
          }
        case 120: break;
        case 48: 
          { lexeme = yytext(); return Class;
          }
        case 121: break;
        case 14: 
          { lexeme = yytext();return Parentesis_A;
          }
        case 122: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
