/* The following code was generated by JFlex 1.4.3 on 11/10/21 1:28 */

package analizador_lexico;
import static analizador_lexico.Tokens.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 11/10/21 1:28 from the specification file
 * <tt>C:/Feed-IT/Feed-IT/src/analizador_lexico/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\37\2\0\1\3\22\0\1\3\1\50\1\0\1\36"+
    "\1\0\1\45\2\0\1\51\1\52\1\44\1\42\1\3\1\43\1\0"+
    "\1\40\12\2\2\0\1\47\1\41\1\46\2\0\1\1\1\34\1\33"+
    "\1\1\1\32\15\1\1\13\7\1\4\0\1\1\1\0\1\12\1\20"+
    "\1\31\1\16\1\21\1\7\1\15\1\22\1\4\1\27\1\35\1\10"+
    "\1\23\1\5\1\11\1\25\1\1\1\14\1\26\1\6\1\17\1\1"+
    "\1\24\1\1\1\30\1\1\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\22\2\1\4\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\1"+
    "\1\15\1\16\1\2\1\17\12\2\1\17\13\2\1\0"+
    "\1\20\1\21\1\22\1\23\1\24\2\2\1\17\20\2"+
    "\1\0\1\25\17\2";

  private static int [] zzUnpackAction() {
    int [] result = new int[101];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\53\0\126\0\201\0\254\0\327\0\u0102\0\u012d"+
    "\0\u0158\0\u0183\0\u01ae\0\u01d9\0\u0204\0\u022f\0\u025a\0\u0285"+
    "\0\u02b0\0\u02db\0\u0306\0\u0331\0\u035c\0\u0387\0\u03b2\0\u03dd"+
    "\0\u0408\0\u0433\0\53\0\201\0\u045e\0\53\0\u0489\0\u04b4"+
    "\0\u04df\0\53\0\53\0\u050a\0\126\0\u0535\0\u0560\0\u058b"+
    "\0\u05b6\0\u05e1\0\u060c\0\u0637\0\u0662\0\u068d\0\u06b8\0\u06e3"+
    "\0\u070e\0\u0739\0\u0764\0\u078f\0\u07ba\0\u07e5\0\u0810\0\u083b"+
    "\0\u0866\0\u0891\0\u08bc\0\u08e7\0\u0912\0\53\0\53\0\53"+
    "\0\53\0\u093d\0\u0968\0\u0993\0\u09be\0\u09e9\0\u0a14\0\u0a3f"+
    "\0\u0a6a\0\u0a95\0\u0ac0\0\u0aeb\0\u0b16\0\u0b41\0\u0b6c\0\u0b97"+
    "\0\u0bc2\0\u0bed\0\u0c18\0\u0c43\0\u0c6e\0\53\0\u0c99\0\u0cc4"+
    "\0\u0cef\0\u0d1a\0\u0d45\0\u0d70\0\u0d9b\0\u0dc6\0\u0df1\0\u0e1c"+
    "\0\u0e47\0\u0e72\0\u0e9d\0\u0ec8\0\u0ef3";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[101];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\3\1\16\1\17\1\3"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\3\3\1\26"+
    "\1\3\1\27\2\3\1\30\1\5\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\54\0\2\3\1\0\32\3\17\0\1\4\53\0\1\5"+
    "\33\0\1\5\14\0\2\3\1\0\1\3\1\44\1\3"+
    "\1\45\26\3\16\0\2\3\1\0\5\3\1\44\5\3"+
    "\1\46\16\3\16\0\2\3\1\0\5\3\1\47\24\3"+
    "\16\0\2\3\1\0\4\3\1\50\1\51\5\3\1\52"+
    "\16\3\16\0\2\3\1\0\1\53\4\3\1\54\24\3"+
    "\16\0\2\3\1\0\10\3\1\45\21\3\16\0\2\3"+
    "\1\0\1\3\1\55\30\3\16\0\2\3\1\0\2\3"+
    "\1\56\27\3\16\0\2\3\1\0\5\3\1\57\24\3"+
    "\16\0\2\3\1\0\5\3\1\60\24\3\16\0\2\3"+
    "\1\0\5\3\1\61\24\3\16\0\2\3\1\0\4\3"+
    "\1\62\1\3\1\44\23\3\16\0\2\3\1\0\13\3"+
    "\1\63\16\3\16\0\2\3\1\0\6\3\1\64\23\3"+
    "\16\0\2\3\1\0\6\3\1\65\7\3\1\66\13\3"+
    "\16\0\2\3\1\0\10\3\1\67\4\3\1\70\14\3"+
    "\16\0\2\3\1\0\4\3\1\71\1\3\1\72\23\3"+
    "\16\0\2\3\1\0\5\3\1\73\24\3\15\0\37\30"+
    "\1\0\13\30\36\0\1\74\55\0\1\75\4\0\1\76"+
    "\1\77\47\0\1\100\47\0\1\76\52\0\1\77\4\0"+
    "\1\101\45\0\1\101\12\0\2\3\1\0\2\3\1\45"+
    "\27\3\16\0\2\3\1\0\4\3\1\102\25\3\16\0"+
    "\2\3\1\0\24\3\1\45\5\3\16\0\2\3\1\0"+
    "\5\3\1\103\24\3\16\0\2\3\1\0\10\3\1\104"+
    "\21\3\16\0\2\3\1\0\1\3\1\45\30\3\16\0"+
    "\2\3\1\0\11\3\1\105\20\3\16\0\2\3\1\0"+
    "\5\3\1\106\24\3\16\0\2\3\1\0\12\3\1\45"+
    "\17\3\16\0\2\3\1\0\10\3\1\107\21\3\16\0"+
    "\2\3\1\0\30\3\1\110\1\3\16\0\2\3\1\0"+
    "\13\3\1\111\16\3\16\0\2\3\1\0\5\3\1\112"+
    "\24\3\16\0\2\3\1\0\22\3\1\113\7\3\16\0"+
    "\2\3\1\0\17\3\1\114\12\3\16\0\2\3\1\0"+
    "\22\3\1\115\7\3\16\0\2\3\1\0\2\3\1\116"+
    "\27\3\16\0\2\3\1\0\1\117\14\3\1\52\14\3"+
    "\16\0\2\3\1\0\15\3\1\120\14\3\16\0\2\3"+
    "\1\0\22\3\1\121\7\3\16\0\2\3\1\0\6\3"+
    "\1\122\23\3\16\0\2\3\1\0\1\3\1\123\30\3"+
    "\16\0\2\3\1\0\1\3\1\124\30\3\15\0\36\74"+
    "\1\125\14\74\41\0\1\126\12\0\2\3\1\0\4\3"+
    "\1\45\25\3\16\0\2\3\1\0\6\3\1\44\23\3"+
    "\16\0\2\3\1\0\26\3\1\127\3\3\16\0\2\3"+
    "\1\0\16\3\1\44\13\3\16\0\2\3\1\0\21\3"+
    "\1\45\10\3\16\0\2\3\1\0\1\130\31\3\16\0"+
    "\2\3\1\0\6\3\1\131\23\3\16\0\2\3\1\0"+
    "\14\3\1\117\15\3\16\0\2\3\1\0\4\3\1\132"+
    "\25\3\16\0\2\3\1\0\15\3\1\45\14\3\16\0"+
    "\2\3\1\0\15\3\1\133\14\3\16\0\2\3\1\0"+
    "\6\3\1\134\23\3\16\0\2\3\1\0\15\3\1\13"+
    "\14\3\16\0\2\3\1\0\4\3\1\113\25\3\16\0"+
    "\2\3\1\0\17\3\1\135\12\3\16\0\2\3\1\0"+
    "\5\3\1\45\24\3\16\0\2\3\1\0\22\3\1\136"+
    "\7\3\16\0\2\3\1\0\12\3\1\137\17\3\16\0"+
    "\2\3\1\0\22\3\1\44\7\3\15\0\36\74\1\125"+
    "\1\74\1\30\12\74\1\0\2\3\1\0\6\3\1\140"+
    "\23\3\16\0\2\3\1\0\1\3\1\141\30\3\16\0"+
    "\2\3\1\0\25\3\1\142\4\3\16\0\2\3\1\0"+
    "\15\3\1\143\14\3\16\0\2\3\1\0\12\3\1\144"+
    "\17\3\16\0\2\3\1\0\23\3\1\113\6\3\16\0"+
    "\2\3\1\0\1\121\31\3\16\0\2\3\1\0\22\3"+
    "\1\45\7\3\16\0\2\3\1\0\1\102\31\3\16\0"+
    "\2\3\1\0\25\3\1\145\4\3\16\0\2\3\1\0"+
    "\11\3\1\45\20\3\16\0\2\3\1\0\31\3\1\45"+
    "\16\0\2\3\1\0\6\3\1\52\23\3\16\0\2\3"+
    "\1\0\6\3\1\55\23\3\16\0\2\3\1\0\16\3"+
    "\1\45\13\3\15\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3870];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\30\1\1\11\2\1\1\11\3\1\2\11"+
    "\30\1\1\0\1\1\4\11\23\1\1\0\1\11\17\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[101];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 130) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 20: 
          { return DiferenteDe;
          }
        case 22: break;
        case 6: 
          { return Asignacion;
          }
        case 23: break;
        case 14: 
          { return Parentesis_D;
          }
        case 24: break;
        case 21: 
          { return ExactamenteIgual;
          }
        case 25: break;
        case 19: 
          { return Potencia;
          }
        case 26: break;
        case 16: 
          { return Igual;
          }
        case 27: break;
        case 9: 
          { return Multiplicacion;
          }
        case 28: break;
        case 7: 
          { return Suma;
          }
        case 29: break;
        case 3: 
          { lexeme = yytext(); return Number;
          }
        case 30: break;
        case 2: 
          { lexeme = yytext(); return Identifier;
          }
        case 31: break;
        case 10: 
          { return Modulo;
          }
        case 32: break;
        case 17: 
          { return MayorIgualQue;
          }
        case 33: break;
        case 11: 
          { return MayorQue;
          }
        case 34: break;
        case 5: 
          { return Division;
          }
        case 35: break;
        case 8: 
          { return Resta;
          }
        case 36: break;
        case 15: 
          { lexeme = yytext(); return Reserved;
          }
        case 37: break;
        case 12: 
          { return MenorQue;
          }
        case 38: break;
        case 1: 
          { return ERROR;
          }
        case 39: break;
        case 13: 
          { return Parentesis_I;
          }
        case 40: break;
        case 4: 
          { /*Ignore*/
          }
        case 41: break;
        case 18: 
          { return MenorIgualQue;
          }
        case 42: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
